#####################
#   __  __ _  _ _   #
#  |  \/ _| \| | |  #
#  | o )_ \ \\ | |  #
#  |__/|__/_|\_|_|  #
#                   #
#####################

nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  volumes:
    - $PWD:/app
  ports:
    - "8000:80"

mysql:
  image: percona:5.6
  volumes:
    - $PWD/images/mysql_data:/var/lib/mysql
  ports:
    - "172.17.0.1:3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: cLBoT8e0bzjzhIkdcbzJ
      MYSQL_PORT: 3306
      MYSQL_DATABASE: dsni
      MYSQL_USERNAME: dsni
      MYSQL_PASSWORD: xt03PdYzcquYs86acy0J

php:
  build: images/php
  volumes:
    - $PWD:/app
    - $PWD/images/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    # - $HOME/.ssh/dsni-composer-keyaqui:/root/.ssh/dsni-composer-keyaqui
    # - $HOME/.ssh/dsni-composer-keyaqui.pub:/root/.ssh/dsni-composer-keyaqui.pub
    # - $HOME/.composer/auth.json:/root/.composer/auth.json
  working_dir: /app/public
  ports:
    - "9000:9000"
  environment:
      CENSUS_DOCKER_APP: "TRUE"
      CENSUS_APIKEY: Example-U6ufn1MMMFWPqMqMnOnRnaZcJ41aaqIM
      GOOGLE_API_KEY: Example-6cB49Yh48_Example-fI8SuWZNE6AGX
  links:
    - mysql